#define BINDIR "/home/local/ameinand/MDRANGE/mdrange/bin/"
#define DATADIR "/home/local/ameinand/MDRANGE/mdrange/data/"
#define F_ELEMENTS "/home/local/ameinand/MDRANGE/mdrange/data/mass93.str"
#define F_SCOEFA "/home/local/ameinand/MDRANGE/mdrange/data/scoef.95a"
#define F_SCOEFB "/home/local/ameinand/MDRANGE/mdrange/data/scoef.95b"
